# -*- coding: utf-8 -*-
"""read_nc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KDbfOvrBn9-ni9v6myxAgx5_4zq26u0j
"""

import xarray as xr

data = xr.open_dataset('/content/drive/MyDrive/Colab Notebooks/CH_1981_2020.nc')

precip = data['precip'].to_series()

print(precip)
precip.to_csv('/content/drive/MyDrive/Colab Notebooks/precipitation.csv',index=True, header=True)
