# -*- coding: utf-8 -*-
"""read_nc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KDbfOvrBn9-ni9v6myxAgx5_4zq26u0j
"""

import xarray as xr

data = xr.open_dataset('/content/drive/MyDrive/Colab Notebooks/CH_1981_2020.nc')

precip = data['precip'].to_series()

print(precip)
precip.to_csv('/content/drive/MyDrive/Colab Notebooks/precipitation.csv',index=True, header=True)


#read csv 
import pandas as pd
#menjadikan kolom ke-0 sebagai index
precip_csv = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Coaching/precipitation.csv', index_col=0, parse_dates=True)

precip_csv.head(3)
precip_csv.tail(4)

precip_csv.dtypes

